# Generated by Django 6.0.7 on 2026-07-22 05:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=16)),
                ('sort_order', models.PositiveIntegerField(unique=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('simulation_key', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Use a lowercase kebab-case registry key.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
            ],
            options={
                'ordering': ('sort_order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('url', models.URLField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('question_type', models.CharField(choices=[('single', 'Single answer'), ('multiple', 'Multiple answers')], default='single', max_length=12)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='lessons.lesson')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependent_links', to='lessons.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', through='lessons.LessonPrerequisite', to='lessons.lesson'),
        ),
        migrations.CreateModel(
            name='LessonRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lesson_revisions', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='lessons.lesson')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_lesson_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('lesson', '-version'),
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lessons.lessonrevision')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('block_type', models.CharField(choices=[('narrative', 'Narrative'), ('callout', 'Callout'), ('code', 'Code sample'), ('terminal', 'Terminal'), ('image', 'Image'), ('simulation', 'Simulation')], max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_blocks', to='lessons.mediaasset')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lessons.lessonsection')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LessonSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=200)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.lessonsection')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('ready', 'Ready')], default='draft', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.lessonrevision')),
            ],
            options={
                'ordering': ('revision', 'locale'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lessons.question')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_percentage', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_answers', models.BooleanField(default=False)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lessons.lessonrevision')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.quiz'),
        ),
        migrations.CreateModel(
            name='QuizTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('text', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.answer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('answer', 'locale'), name='unique_answer_locale')],
            },
        ),
        migrations.CreateModel(
            name='LessonBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='lessons.lessonblock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'locale'), name='unique_block_locale')],
            },
        ),
        migrations.AddConstraint(
            model_name='lessonprerequisite',
            constraint=models.UniqueConstraint(fields=('lesson', 'prerequisite'), name='unique_lesson_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='lessonprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('lesson', models.F('prerequisite')), _negated=True), name='lesson_cannot_require_itself'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', 'sort_order'], name='lesson_catalog_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonrevision',
            constraint=models.UniqueConstraint(fields=('lesson', 'version'), name='unique_lesson_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='lessonrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('lesson',), name='one_published_revision_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status', 'published')), models.Q(('status', 'published'), _negated=True), _connector='OR'), name='published_revision_has_audit_fields'),
        ),
        migrations.AddConstraint(
            model_name='lessonsection',
            constraint=models.UniqueConstraint(fields=('revision', 'key'), name='unique_revision_section_key'),
        ),
        migrations.AddConstraint(
            model_name='lessonsection',
            constraint=models.UniqueConstraint(fields=('revision', 'sort_order'), name='unique_revision_section_order'),
        ),
        migrations.AddConstraint(
            model_name='lessonblock',
            constraint=models.UniqueConstraint(fields=('section', 'key'), name='unique_section_block_key'),
        ),
        migrations.AddConstraint(
            model_name='lessonblock',
            constraint=models.UniqueConstraint(fields=('section', 'sort_order'), name='unique_section_block_order'),
        ),
        migrations.AddConstraint(
            model_name='lessonsectiontranslation',
            constraint=models.UniqueConstraint(fields=('section', 'locale'), name='unique_section_locale'),
        ),
        migrations.AddConstraint(
            model_name='lessontranslation',
            constraint=models.UniqueConstraint(fields=('revision', 'locale'), name='unique_lesson_revision_locale'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'key'), name='unique_question_answer_key'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'sort_order'), name='unique_question_answer_order'),
        ),
        migrations.AddConstraint(
            model_name='questiontranslation',
            constraint=models.UniqueConstraint(fields=('question', 'locale'), name='unique_question_locale'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'key'), name='unique_quiz_question_key'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'sort_order'), name='unique_quiz_question_order'),
        ),
        migrations.AddConstraint(
            model_name='quiztranslation',
            constraint=models.UniqueConstraint(fields=('quiz', 'locale'), name='unique_quiz_locale'),
        ),
    ]
