# Generated by Django 6.0.7 on 2026-07-26 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_lessonblocktranslation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('total_steps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interactive_completed_at', models.DateTimeField(blank=True, null=True)),
                ('guide_completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_completed_at', models.DateTimeField(blank=True, null=True)),
                ('best_quiz_score', models.PositiveSmallIntegerField(default=0)),
                ('best_quiz_total', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='lessons.lesson')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_progress', to='lessons.lessonrevision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity_at', '-updated_at'),
                'indexes': [models.Index(fields=['user', '-last_activity_at'], name='progress_recent_idx'), models.Index(fields=['lesson', 'revision'], name='progress_lesson_rev_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_progress'), models.CheckConstraint(condition=models.Q(('total_steps__isnull', True), ('current_step__lte', models.F('total_steps')), _connector='OR'), name='progress_current_step_lte_total_steps'), models.CheckConstraint(condition=models.Q(('best_quiz_score__lte', models.F('best_quiz_total')), ('best_quiz_total', 0), _connector='OR'), name='progress_best_score_lte_total')],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='lessons.lesson')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_attempts', to='lessons.lessonrevision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_at', '-id'),
                'indexes': [models.Index(fields=['user', '-completed_at'], name='quiz_attempt_recent_idx'), models.Index(fields=['lesson', 'revision'], name='quiz_attempt_lesson_rev_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_questions__gt', 0)), name='quiz_attempt_total_questions_gt_zero'), models.CheckConstraint(condition=models.Q(('score__lte', models.F('total_questions'))), name='quiz_attempt_score_lte_total')],
            },
        ),
    ]
