# Generated by Django 6.0.7 on 2026-07-26 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lessonbookmark'),
        ('lessons', '0002_lessonblocktranslation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningXpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_slug', models.SlugField(max_length=120)),
                ('event_type', models.CharField(choices=[('lesson_started', 'Lesson started'), ('interactive_completed', 'Interactive completed'), ('guide_completed', 'Guide completed'), ('quiz_passed', 'Quiz passed'), ('quiz_first_try', 'Quiz first try'), ('lesson_completed', 'Lesson completed')], max_length=32)),
                ('xp_amount', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='lessons.lesson')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='lessons.lessonrevision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='xp_event_recent_idx'), models.Index(fields=['user', 'lesson_slug'], name='xp_event_user_lesson_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson_slug', 'event_type'), name='unique_user_lesson_xp_event'), models.CheckConstraint(condition=models.Q(('xp_amount__gt', 0)), name='xp_event_amount_gt_zero')],
            },
        ),
    ]
