# Generated by Django 6.0.7 on 2026-07-26 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_learningxpevent'),
        ('lessons', '0002_lessonblocktranslation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('lesson_slug', models.SlugField(blank=True, max_length=120)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_unlocks', to='lessons.lesson')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievement_unlocks', to='lessons.lessonrevision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-unlocked_at', '-id'),
                'indexes': [models.Index(fields=['user', '-unlocked_at'], name='achievement_recent_idx'), models.Index(fields=['code', '-unlocked_at'], name='achievement_code_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='unique_user_learning_achievement')],
            },
        ),
    ]
