# Generated by Django 6.0.7 on 2026-07-26 11:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningachievement'),
        ('lessons', '0002_lessonblocktranslation_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('sort_order', models.PositiveIntegerField(unique=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=45)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'slug'),
                'indexes': [models.Index(fields=['status', 'sort_order'], name='path_catalog_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningPathLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_path_links', to='lessons.lesson')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_lessons', to='learning.learningpath')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('path', 'lesson'), name='unique_learning_path_lesson'), models.UniqueConstraint(fields=('path', 'sort_order'), name='unique_learning_path_lesson_order')],
            },
        ),
        migrations.CreateModel(
            name='LearningPathTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning.learningpath')),
            ],
            options={
                'ordering': ('path', 'locale'),
                'constraints': [models.UniqueConstraint(fields=('path', 'locale'), name='unique_learning_path_locale')],
            },
        ),
    ]
