# Generated by Django 6.0.7 on 2026-07-27 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningpath_learningpathlesson_and_more'),
        ('lessons', '0002_lessonblocktranslation_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(choices=[('too_easy', 'Too easy'), ('just_right', 'Just right'), ('too_hard', 'Too hard')], default='just_right', max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('quiz', 'Quiz'), ('guide', 'Guide'), ('lesson', 'Lesson')], default='quiz', max_length=16)),
                ('locale', models.CharField(default='fa', max_length=10, validators=[django.core.validators.RegexValidator(message="Use a locale such as 'fa', 'en', or 'en-US'.", regex='^[a-z]{2,3}(?:-[A-Z]{2})?$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='lessons.lesson')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='lessons.lessonrevision')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
                'indexes': [models.Index(fields=['lesson', '-updated_at'], name='feedback_lesson_recent_idx'), models.Index(fields=['user', '-updated_at'], name='feedback_user_recent_idx'), models.Index(fields=['rating', 'difficulty'], name='feedback_quality_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_feedback'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_between_1_and_5')],
            },
        ),
    ]
